<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.2.2 (Python 3.13.2 on linux)" generated="2025-04-08T19:53:07.161280" rpa="false" schemaversion="5">
<suite id="s1" name="Simple" source="/home/dhandyjoee/Documents/kreditplus/automation/poc-robotframework-selenium/e2e/simple.robot">
<test id="s1-t1" name="test valid login" line="11">
<kw name="Open Browser" owner="SeleniumLibrary">
<msg time="2025-04-08T19:53:07.243964" level="INFO">Opening browser 'Chrome' to base url 'https://staging-sally.kbfinansia.com/auth/login'.</msg>
<msg time="2025-04-08T19:53:09.924336" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f1997c45450&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/85fc5a10f3853b633290cc140cab6407/screenshot</msg>
<msg time="2025-04-08T19:53:09.924947" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f1997c451d0&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/85fc5a10f3853b633290cc140cab6407/screenshot</msg>
<msg time="2025-04-08T19:53:09.925373" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f1997d27820&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/85fc5a10f3853b633290cc140cab6407/screenshot</msg>
<msg time="2025-04-08T19:53:09.925722" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=41033): Max retries exceeded with url: /session/85fc5a10f3853b633290cc140cab6407/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f1997d27bb0&gt;: Failed to establish a new connection: [Errno 111] Connection refused'))</msg>
<arg>${LOGIN URL}</arg>
<arg>${BROWSER}</arg>
<arg>options=${CHROME_OPTIONS}</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<status status="FAIL" start="2025-04-08T19:53:07.243713" elapsed="2.682118">Execution terminated by signal</status>
</kw>
<kw name="Input Text" owner="SeleniumLibrary">
<arg>xpath://input[@id='username']</arg>
<arg>dhandyjoenathan</arg>
<doc>Types the given ``text`` into the text field identified by ``locator``.</doc>
<status status="NOT RUN" start="2025-04-08T19:53:09.926031" elapsed="0.000089"/>
</kw>
<kw name="Input Text" owner="SeleniumLibrary">
<arg>xpath://input[@id='password']</arg>
<arg>201017Dj*#*#</arg>
<doc>Types the given ``text`` into the text field identified by ``locator``.</doc>
<status status="NOT RUN" start="2025-04-08T19:53:09.926244" elapsed="0.000022"/>
</kw>
<kw name="Click Element" owner="SeleniumLibrary">
<arg>xpath://button[normalize-space()='LOGIN']</arg>
<doc>Click the element identified by ``locator``.</doc>
<status status="NOT RUN" start="2025-04-08T19:53:09.926355" elapsed="0.000025"/>
</kw>
<kw name="Wait Until Element Is Visible" owner="SeleniumLibrary">
<arg>xpath://h3[normalize-space()='Profile']</arg>
<doc>Waits until the element ``locator`` is visible.</doc>
<status status="NOT RUN" start="2025-04-08T19:53:09.926495" elapsed="0.000027"/>
</kw>
<kw name="Element Should Be Visible" owner="SeleniumLibrary">
<arg>xpath://h3[normalize-space()='Profile']</arg>
<doc>Verifies that the element identified by ``locator`` is visible.</doc>
<status status="NOT RUN" start="2025-04-08T19:53:09.926611" elapsed="0.000017"/>
</kw>
<kw name="Element Text Should Be" owner="SeleniumLibrary">
<arg>xpath://h3[normalize-space()='Profile']</arg>
<arg>Profile</arg>
<doc>Verifies that element ``locator`` contains exact the text ``expected``.</doc>
<status status="NOT RUN" start="2025-04-08T19:53:09.926697" elapsed="0.000016"/>
</kw>
<kw name="logoutSallyWeb">
<status status="NOT RUN" start="2025-04-08T19:53:09.926884" elapsed="0.000026"/>
</kw>
<status status="FAIL" start="2025-04-08T19:53:07.243035" elapsed="2.684027">Execution terminated by signal</status>
</test>
<test id="s1-t2" name="test invalid login" line="21">
<tag>robot:exit</tag>
<status status="FAIL" start="2025-04-08T19:53:09.927245" elapsed="0.000214">Test execution stopped due to a fatal error.</status>
</test>
<test id="s1-t3" name="test null username password" line="31">
<tag>robot:exit</tag>
<status status="FAIL" start="2025-04-08T19:53:09.927591" elapsed="0.000229">Test execution stopped due to a fatal error.</status>
</test>
<doc>Simple example using SeleniumLibrary.</doc>
<status status="FAIL" start="2025-04-08T19:53:07.161817" elapsed="2.766453"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="3" skip="0">All Tests</stat>
</total>
<tag>
<stat info="combined" combined="NOT robot:exit" pass="0" fail="1" skip="0">NOT robot:exit</stat>
</tag>
<suite>
<stat name="Simple" id="s1" pass="0" fail="3" skip="0">Simple</stat>
</suite>
</statistics>
<errors>
<msg time="2025-04-08T19:53:09.924336" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f1997c45450&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/85fc5a10f3853b633290cc140cab6407/screenshot</msg>
<msg time="2025-04-08T19:53:09.924947" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f1997c451d0&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/85fc5a10f3853b633290cc140cab6407/screenshot</msg>
<msg time="2025-04-08T19:53:09.925373" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f1997d27820&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/85fc5a10f3853b633290cc140cab6407/screenshot</msg>
<msg time="2025-04-08T19:53:09.925722" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=41033): Max retries exceeded with url: /session/85fc5a10f3853b633290cc140cab6407/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f1997d27bb0&gt;: Failed to establish a new connection: [Errno 111] Connection refused'))</msg>
</errors>
</robot>
